# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from miniRover/imInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class imInfo(genpy.Message):
  _md5sum = "79b15cecdb5c3ec4ca33b4244b61fb45"
  _type = "miniRover/imInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# message describing the processed img info for path following purposes
int32 x_im_midpt
int32 x_midpt_frm_lines
int32 x_im_intercept_l
int32 x_im_intercept_r"""
  __slots__ = ['x_im_midpt','x_midpt_frm_lines','x_im_intercept_l','x_im_intercept_r']
  _slot_types = ['int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x_im_midpt,x_midpt_frm_lines,x_im_intercept_l,x_im_intercept_r

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(imInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x_im_midpt is None:
        self.x_im_midpt = 0
      if self.x_midpt_frm_lines is None:
        self.x_midpt_frm_lines = 0
      if self.x_im_intercept_l is None:
        self.x_im_intercept_l = 0
      if self.x_im_intercept_r is None:
        self.x_im_intercept_r = 0
    else:
      self.x_im_midpt = 0
      self.x_midpt_frm_lines = 0
      self.x_im_intercept_l = 0
      self.x_im_intercept_r = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4i.pack(_x.x_im_midpt, _x.x_midpt_frm_lines, _x.x_im_intercept_l, _x.x_im_intercept_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.x_im_midpt, _x.x_midpt_frm_lines, _x.x_im_intercept_l, _x.x_im_intercept_r,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4i.pack(_x.x_im_midpt, _x.x_midpt_frm_lines, _x.x_im_intercept_l, _x.x_im_intercept_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.x_im_midpt, _x.x_midpt_frm_lines, _x.x_im_intercept_l, _x.x_im_intercept_r,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4i = struct.Struct("<4i")
